import type { Course, Category, Testimonial, Instructor } from '@/types';

export const INSTRUCTORS: Instructor[] = [
  {
    id: '1',
    name: 'Dr. Carlos Mendoza',
    title: 'Especialista en Gestion Publica',
    avatar: '/instructors/carlos-mendoza.jpg',
    bio: 'Doctor en Administracion Publica con mas de 15 anos de experiencia en el sector publico peruano.',
    courseCount: 12,
    studentCount: 15000,
    rating: 4.9,
  },
  {
    id: '2',
    name: 'Lic. Maria Fernandez',
    title: 'Experta en Recursos Humanos',
    avatar: '/instructors/maria-fernandez.jpg',
    bio: 'Licenciada en Psicologia Organizacional, especialista en gestion del talento humano.',
    courseCount: 8,
    studentCount: 12000,
    rating: 4.8,
  },
  {
    id: '3',
    name: 'Mg. Roberto Silva',
    title: 'Contador Publico Colegiado',
    avatar: '/instructors/roberto-silva.jpg',
    bio: 'Magister en Contabilidad y Finanzas, experto en normativa tributaria peruana.',
    courseCount: 15,
    studentCount: 20000,
    rating: 4.9,
  },
  {
    id: '4',
    name: 'Dra. Ana Torres',
    title: 'Especialista en Salud Publica',
    avatar: '/instructors/ana-torres.jpg',
    bio: 'Doctora en Salud Publica con experiencia en el MINSA y organizaciones internacionales.',
    courseCount: 10,
    studentCount: 8000,
    rating: 4.7,
  },
];

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Administracion Publica',
    slug: 'administracion-publica',
    description: 'Cursos especializados en gestion y administracion del sector publico peruano.',
    icon: 'Building2',
    courseCount: 45,
    color: 'bg-blue-500',
  },
  {
    id: '2',
    name: 'Salud',
    slug: 'salud',
    description: 'Formacion para profesionales de la salud con certificacion valida.',
    icon: 'Heart',
    courseCount: 38,
    color: 'bg-red-500',
  },
  {
    id: '3',
    name: 'Educacion',
    slug: 'educacion',
    description: 'Capacitacion docente y pedagogica con horas cronologicas certificadas.',
    icon: 'GraduationCap',
    courseCount: 52,
    color: 'bg-green-500',
  },
  {
    id: '4',
    name: 'Derecho',
    slug: 'derecho',
    description: 'Actualizacion juridica y legal para profesionales del derecho.',
    icon: 'Scale',
    courseCount: 28,
    color: 'bg-purple-500',
  },
  {
    id: '5',
    name: 'Gestion Empresarial',
    slug: 'gestion-empresarial',
    description: 'Habilidades de gestion y liderazgo para el mundo empresarial.',
    icon: 'Briefcase',
    courseCount: 35,
    color: 'bg-orange-500',
  },
  {
    id: '6',
    name: 'Tecnologia',
    slug: 'tecnologia',
    description: 'Cursos de tecnologia, programacion y transformacion digital.',
    icon: 'Laptop',
    courseCount: 42,
    color: 'bg-cyan-500',
  },
  {
    id: '7',
    name: 'Contabilidad',
    slug: 'contabilidad',
    description: 'Contabilidad, finanzas y normativa tributaria actualizada.',
    icon: 'Calculator',
    courseCount: 30,
    color: 'bg-emerald-500',
  },
  {
    id: '8',
    name: 'Recursos Humanos',
    slug: 'recursos-humanos',
    description: 'Gestion del talento humano y desarrollo organizacional.',
    icon: 'Users',
    courseCount: 25,
    color: 'bg-pink-500',
  },
];

export const COURSES: Course[] = [
  {
    id: '1',
    title: 'Gestion Publica y Modernizacion del Estado',
    slug: 'gestion-publica-modernizacion-estado',
    description: 'Aprende los fundamentos de la gestion publica moderna y las reformas del Estado peruano. Curso completo con enfoque practico.',
    shortDescription: 'Fundamentos de la gestion publica moderna en Peru.',
    instructor: INSTRUCTORS[0],
    category: CATEGORIES[0],
    certificateType: 'certificado',
    hours: 60,
    price: 149,
    originalPrice: 299,
    rating: 4.9,
    reviewCount: 1250,
    studentCount: 5420,
    image: '/courses/gestion-publica.jpg',
    featured: true,
    bestseller: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Sistema Integrado de Administracion Financiera (SIAF)',
    slug: 'siaf-sistema-integrado-administracion-financiera',
    description: 'Domina el SIAF-SP: registro de operaciones, ejecucion presupuestal y reportes financieros del sector publico.',
    shortDescription: 'Aprende a usar el SIAF-SP de manera practica.',
    instructor: INSTRUCTORS[2],
    category: CATEGORIES[0],
    certificateType: 'diploma',
    hours: 120,
    price: 249,
    originalPrice: 399,
    rating: 4.8,
    reviewCount: 890,
    studentCount: 3200,
    image: '/courses/siaf.jpg',
    featured: true,
    bestseller: true,
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    title: 'Contrataciones del Estado - Ley 30225',
    slug: 'contrataciones-estado-ley-30225',
    description: 'Todo sobre la Ley de Contrataciones del Estado y su Reglamento. Incluye casos practicos y actualizaciones normativas.',
    shortDescription: 'Ley de Contrataciones del Estado actualizada.',
    instructor: INSTRUCTORS[0],
    category: CATEGORIES[0],
    certificateType: 'certificado',
    hours: 48,
    price: 129,
    originalPrice: 249,
    rating: 4.9,
    reviewCount: 2100,
    studentCount: 8500,
    image: '/courses/contrataciones.jpg',
    featured: true,
    bestseller: true,
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    title: 'Excel Avanzado para la Gestion Publica',
    slug: 'excel-avanzado-gestion-publica',
    description: 'Excel avanzado con enfoque en reportes, dashboards y automatizacion para el sector publico.',
    shortDescription: 'Excel avanzado aplicado al sector publico.',
    instructor: INSTRUCTORS[2],
    category: CATEGORIES[5],
    certificateType: 'constancia',
    hours: 24,
    price: 79,
    originalPrice: 149,
    rating: 4.7,
    reviewCount: 1560,
    studentCount: 6200,
    image: '/courses/excel.jpg',
    featured: false,
    bestseller: true,
    createdAt: '2024-03-01',
  },
  {
    id: '5',
    title: 'Gestion de Recursos Humanos en el Sector Publico',
    slug: 'gestion-recursos-humanos-sector-publico',
    description: 'Gestion del talento humano bajo el regimen SERVIR. Incluye procesos CAS, evaluacion de desempeno y desarrollo de personal.',
    shortDescription: 'RRHH en el sector publico bajo regimen SERVIR.',
    instructor: INSTRUCTORS[1],
    category: CATEGORIES[7],
    certificateType: 'certificado',
    hours: 50,
    price: 159,
    originalPrice: 299,
    rating: 4.8,
    reviewCount: 720,
    studentCount: 2800,
    image: '/courses/rrhh-publico.jpg',
    featured: true,
    bestseller: false,
    createdAt: '2024-02-15',
  },
  {
    id: '6',
    title: 'Primeros Auxilios y RCP Basico',
    slug: 'primeros-auxilios-rcp-basico',
    description: 'Aprende tecnicas de primeros auxilios y reanimacion cardiopulmonar. Certificado valido para trabajadores de salud.',
    shortDescription: 'Primeros auxilios y RCP con certificacion.',
    instructor: INSTRUCTORS[3],
    category: CATEGORIES[1],
    certificateType: 'constancia',
    hours: 16,
    price: 59,
    originalPrice: 99,
    rating: 4.9,
    reviewCount: 3200,
    studentCount: 12000,
    image: '/courses/primeros-auxilios.jpg',
    featured: false,
    bestseller: true,
    createdAt: '2024-01-10',
  },
  {
    id: '7',
    title: 'Didactica y Pedagogia para Docentes',
    slug: 'didactica-pedagogia-docentes',
    description: 'Estrategias didacticas innovadoras y enfoques pedagogicos actuales para mejorar tu practica docente.',
    shortDescription: 'Mejora tu practica docente con estrategias modernas.',
    instructor: INSTRUCTORS[1],
    category: CATEGORIES[2],
    certificateType: 'certificado',
    hours: 80,
    price: 179,
    originalPrice: 349,
    rating: 4.8,
    reviewCount: 980,
    studentCount: 4100,
    image: '/courses/pedagogia.jpg',
    featured: true,
    bestseller: false,
    createdAt: '2024-02-20',
  },
  {
    id: '8',
    title: 'Procedimiento Administrativo General',
    slug: 'procedimiento-administrativo-general',
    description: 'Ley 27444 - TUO de la Ley del Procedimiento Administrativo General. Incluye silencio administrativo y recursos.',
    shortDescription: 'Ley 27444 explicada con casos practicos.',
    instructor: INSTRUCTORS[0],
    category: CATEGORIES[3],
    certificateType: 'certificado',
    hours: 40,
    price: 119,
    originalPrice: 229,
    rating: 4.7,
    reviewCount: 650,
    studentCount: 2400,
    image: '/courses/procedimiento-admin.jpg',
    featured: false,
    bestseller: false,
    createdAt: '2024-03-10',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Juan Carlos Quispe',
    role: 'Servidor Publico',
    company: 'Ministerio de Economia y Finanzas',
    avatar: '/testimonials/juan-carlos.jpg',
    content: 'Gracias a los cursos de CertificadosPeru pude obtener los puntos necesarios para mi proceso CAS. Los certificados fueron aceptados sin ningun problema por la comision evaluadora.',
    rating: 5,
    certificateType: 'certificado',
    courseName: 'Gestion Publica y Modernizacion del Estado',
  },
  {
    id: '2',
    name: 'Maria Elena Rodriguez',
    role: 'Docente',
    company: 'I.E. Nacional de Lima',
    avatar: '/testimonials/maria-elena.jpg',
    content: 'Los cursos de pedagogia me ayudaron a sumar horas para mi evaluacion docente. La plataforma es muy facil de usar y los certificados llegan inmediatamente.',
    rating: 5,
    certificateType: 'certificado',
    courseName: 'Didactica y Pedagogia para Docentes',
  },
  {
    id: '3',
    name: 'Roberto Huaman',
    role: 'Contador',
    company: 'Municipalidad de Miraflores',
    avatar: '/testimonials/roberto.jpg',
    content: 'El curso de SIAF fue exactamente lo que necesitaba. El instructor explica muy bien y los ejercicios practicos son muy utiles para el trabajo diario.',
    rating: 5,
    certificateType: 'diploma',
    courseName: 'Sistema Integrado de Administracion Financiera',
  },
  {
    id: '4',
    name: 'Ana Lucia Chavez',
    role: 'Enfermera',
    company: 'Hospital Nacional',
    avatar: '/testimonials/ana-lucia.jpg',
    content: 'Obtuve mi constancia de Primeros Auxilios rapidamente. La verificacion QR funciona perfectamente y me sirvio para mi postulacion en el hospital.',
    rating: 5,
    certificateType: 'constancia',
    courseName: 'Primeros Auxilios y RCP Basico',
  },
  {
    id: '5',
    name: 'Pedro Sanchez',
    role: 'Abogado',
    company: 'Estudio Juridico Sanchez & Asociados',
    avatar: '/testimonials/pedro.jpg',
    content: 'La actualizacion en Contrataciones del Estado me permitio asesorar mejor a mis clientes del sector publico. Excelente contenido y muy bien estructurado.',
    rating: 5,
    certificateType: 'certificado',
    courseName: 'Contrataciones del Estado - Ley 30225',
  },
];

export const FEATURED_COURSES = COURSES.filter(course => course.featured);
export const BESTSELLER_COURSES = COURSES.filter(course => course.bestseller);
